services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://172.17.0.1:5432/bonus
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres